version: '3'
services:
    oe40:
        container_name: oe40
        build:
            context: .
            dockerfile: Dockerfile
        image: oe40:latest
        env_file: .env
        ports:
            - 80:80
        volumes:
            - .:/var/www/oe40:rw
            - vendor:/var/www/oe40/vendor
            - node_modules:/var/www/oe40/node_modules
        networks:
            - oe40
        depends_on:
            - mysql
            - redis
    mysql:
        container_name: mysql
        image: mysql:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - oe40
    redis:
        container_name: redis
        image: redis:alpine
        ports:
            - 6379:6379
        volumes:
            - redis:/data
        networks:
            - oe40
networks:
    oe40:
        driver: bridge
volumes:
    vendor:
        driver: local
    node_modules:
        driver: local
    mysql:
        driver: local
    redis:
        driver: local
